### ISSUE TITLE
Document the use of authenticate() using ENV variable

### ISSUE THREAD

**Issue by ucorpintegration** [KnpLabs/php-github-api#1085]
In `config/packages/github.yml` , there is:

```
services:
    Github\Client:
        arguments:
            - '@Github\HttpClient\Builder'
        calls:
            - ['authenticate', ['%env(GITHUB_USERNAME)%', '%env(GITHUB_SECRET)%', '%env(GITHUB_AUTH_METHOD)%']]
```

But how to use it?
Not knowing how to use it, I temporarily put the credentials in the code.
